{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0df8118e",
   "metadata": {},
   "source": [
    "# Introducción\n",
    "\n",
    "Incluso el código mejor escrito contendrá errores. Los errores pueden\n",
    "producirse debido a actualizaciones, archivos movidos u otros cambios\n",
    "inesperados. Afortunadamente, Python ofrece una amplia compatibilidad\n",
    "para el seguimiento y el control de errores.\n",
    "\n",
    "## Escenario: Creación de un programa de cohetes\n",
    "\n",
    "Imagina que es un desarrollador que está creando un programa para un\n",
    "cohete. El programa debe leer un archivo de configuración para\n",
    "asegurarse de que se carga la configuración adecuada. La lectura del\n",
    "archivo puede producir un error si falta el archivo o tiene otros\n",
    "problemas. En este módulo, explorarás cómo crear el programa.\n",
    "\n",
    "## ¿Qué descubrirás?\n",
    "\n",
    "Al término de este módulo, sabrás hacer lo siguiente:\n",
    "\n",
    "-   Leer y usar la salida de errores de las excepciones Controlar\n",
    "    correctamente las excepciones\n",
    "-   Generar excepciones con mensajes de error útiles\n",
    "-   Usar excepciones para controlar el flujo de un programa\n",
    "\n",
    "## ¿Cuál es el objetivo principal?\n",
    "\n",
    "En este módulo, descubrirás cómo usar la salida de excepción para la\n",
    "depuración, cómo detectar y generar excepciones, y cómo afecta a la\n",
    "lógica de un programa cuando se producen excepciones.\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "## Uso de tracebacks para buscar errores\n",
    "\n",
    "Las excepciones en Python son una característica principal del lenguaje.\n",
    "Es posible que te sorprenda leer que algo que genera errores se resalta\n",
    "como una característica. Esta sorpresa puede deberse a que las\n",
    "herramientas de software sólidas no parecen bloquearse con un traceback\n",
    "*seguimiento* (varias líneas de texto que indican cómo se inició y\n",
    "finalizó el error).\n",
    "\n",
    "Sin embargo, las excepciones son útiles porque ayudan en la toma de\n",
    "decisiones generando mensajes de error descriptivos. Pueden ayudarte a\n",
    "controlar los problemas esperados e inesperados.\n",
    "\n",
    "## Tracebacks\n",
    "\n",
    "Un traceback es el cuerpo del texto que puede apuntar al origen (y al\n",
    "final) de un error no controlado. Comprender los componentes de un\n",
    "traceback hará que seas más eficaz al corregir errores o depurar un\n",
    "programa que no funciona bien.\n",
    "\n",
    "La primera vez que encuentres excepciones en Python podrías verte\n",
    "tentado/a a evitar el error suprimiéndolo. Cuando un programa sufre un\n",
    "error no controlado, aparece un traceback como salida. Como verás en\n",
    "este módulo, los tracebacks son útiles. Hay maneras de controlar\n",
    "correctamente los errores para que no aparezcan o muestren información\n",
    "útil.\n",
    "\n",
    "Si intentamos en un notebook, abrir un archivo inexistente sucede lo\n",
    "siguiente:\n",
    "\n",
    "    >>> open(\"/path/to/mars.jpg\")\n",
    "    Traceback (most recent call last):\n",
    "      File \"<stdin>\", line 1, in <module>\n",
    "    FileNotFoundError: [Errno 2] No such file or directory: '/path/to/mars.jpg'\n",
    "\n",
    "Esa salida tiene varias partes clave. En primer lugar, el traceback\n",
    "menciona el orden de la salida. Después, informa de que el archivo es\n",
    "`stdin` (entrada en el terminal interactivo) en la primera línea de la\n",
    "entrada. El error es `FileNotFoundError` (el nombre de excepción), lo\n",
    "que significa que el archivo no existe o quizás el directorio\n",
    "correspondiente no existe.\n",
    "\n",
    "Es mucha información. Puede ser difícil entender por qué la línea 1 es\n",
    "significativa o qué significa `Errno 2`.\n",
    "\n",
    "Intenta crear un archivo de Python y asígnale el nombre *open.py*, con\n",
    "el contenido siguiente:\n",
    "\n",
    "    def main():\n",
    "        open(\"/path/to/mars.jpg\")\n",
    "\n",
    "    if __name__ == '__main__':\n",
    "        main()\n",
    "\n",
    "Se trata de una sola función `main()` que abre el archivo inexistente,\n",
    "como antes. Al final, esta función usa un asistente de Python que indica\n",
    "al intérprete que ejecute la función `main()` cuando se le llama en el\n",
    "terminal. Ejecútala con Python y podrás comprobar el siguiente mensaje\n",
    "de error:\n",
    "\n",
    "    $ python3 open.py\n",
    "    Traceback (most recent call last):\n",
    "      File \"/tmp/open.py\", line 5, in <module>\n",
    "        main()\n",
    "      File \"/tmp/open.py\", line 2, in main\n",
    "        open(\"/path/to/mars.jpg\")\n",
    "    FileNotFoundError: [Errno 2] No such file or directory: '/path/to/mars.jpg'\n",
    "\n",
    "La salida de error tiene más sentido ahora. Las rutas de acceso apuntan\n",
    "a un único archivo denominado *open.py*. La salida menciona que el error\n",
    "se inicia en la línea 5, que incluye la llamada a `main()`. A\n",
    "continuación, la salida sigue el error a la línea 2 en la llamada de\n",
    "función `open()`. Y, por último, `FileNotFoundError` notifica de nuevo\n",
    "que el archivo o el directorio no existen.\n",
    "\n",
    "Los tracebacks casi siempre incluyen la información siguiente:\n",
    "\n",
    "-   Todas las rutas de acceso de archivo implicadas, para cada llamada a\n",
    "    cada función.\n",
    "-   Los números de línea asociados a cada ruta de acceso de archivo.\n",
    "-   Los nombres de las funciones, métodos o clases implicados en la\n",
    "    generación de una excepción.\n",
    "-   El nombre de la excepción que se ha producido.\n",
    "\n",
    "## Controlando las excepciones\n",
    "\n",
    "Cuando encuentres por primera vez excepciones que muestren tracebacks\n",
    "grandes como salida, es posible que te veas tentado/a a detectar todos\n",
    "los errores para evitar que esto suceda.\n",
    "\n",
    "Si estás en una misión a Marte, ¿Qué podrías hacer si un texto del\n",
    "sistema de navegación dice ‘Se ha producido un error’? Imagina que no\n",
    "hay ninguna más información ni contexto, simplemente una luz roja\n",
    "parpadeante con el texto del error. Como desarrollador, resulta útil\n",
    "ponerse al otro lado del programa: ¿Qué puede hacer un usuario cuando se\n",
    "produce un error?\n",
    "\n",
    "Aunque en este módulo se explica cómo controlar las excepciones\n",
    "detectándolas, no es necesario detectar las excepciones todo el tiempo.\n",
    "A veces resulta útil permitir que se puedan generar excepciones para que\n",
    "otros autores de llamadas puedan tratar los errores.\n",
    "\n",
    "### Try y Except de los bloques\n",
    "\n",
    "Vamos a usar el ejemplo de navegador a fin de crear código que abra\n",
    "archivos de configuración para la misión de Marte. Los archivos de\n",
    "configuración pueden tener todo tipo de problemas, por lo que es\n",
    "fundamental notificarlos con precisión cuando se presenten. Sabemos que,\n",
    "si no existe un archivo o directorio, se genera `FileNotFoundError`. Si\n",
    "queremos controlar esa excepción, podemos hacerlo con un bloque try y\n",
    "except:\n",
    "\n",
    "    >>> try:\n",
    "    ...     open('config.txt')\n",
    "    ... except FileNotFoundError:\n",
    "    ...     print(\"Couldn't find the config.txt file!\")\n",
    "    ...\n",
    "    Couldn't find the config.txt file!\n",
    "\n",
    "Después de la palabra clave `try`, agregamos código que tenga la\n",
    "posibilidad de producir una excepción. A continuación, agregamos la\n",
    "palabra clave `except` junto con la posible excepción, seguida de\n",
    "cualquier código que deba ejecutarse cuando se produce esa condición.\n",
    "Puesto que config.txt no existe en el sistema, Python imprime que el\n",
    "archivo de configuración no está ahí. El bloque `try` y `except`, junto\n",
    "con un mensaje útil, evita un seguimiento y sigue informando al usuario\n",
    "sobre el problema.\n",
    "\n",
    "Aunque es común un archivo que no existe, no es el único error que\n",
    "podemos encontrar. Los permisos de archivo no válidos pueden impedir la\n",
    "lectura de un archivo, incluso si este existe. Vamos a crear un archivo\n",
    "de Python denominado config.py. El archivo tiene código que busca y lee\n",
    "el archivo de configuración del sistema de navegación:\n",
    "\n",
    "    def main():\n",
    "        try:\n",
    "            configuration = open('config.txt')\n",
    "        except FileNotFoundError:\n",
    "            print(\"Couldn't find the config.txt file!\")\n",
    "\n",
    "\n",
    "    if __name__ == '__main__':\n",
    "        main()\n",
    "\n",
    "A continuación, quita,ps el archivo *config.txt* y creamos un directorio\n",
    "denominado *config.txt*. Intentaremos llamar al archivo *config.py* para\n",
    "ver un error nuevo que debería ser similar al siguiente:\n",
    "\n",
    "    $ python config.py\n",
    "    Traceback (most recent call last):\n",
    "      File \"/tmp/config.py\", line 9, in <module>\n",
    "        main()\n",
    "      File \"/tmp/config.py\", line 3, in main\n",
    "        configuration = open('config.txt')\n",
    "    IsADirectoryError: [Errno 21] Is a directory: 'config.txt'\n",
    "\n",
    "Una manera poco útil de controlar este error sería detectar todas las\n",
    "excepciones posibles para evitar un traceback. Para comprender por qué\n",
    "detectar todas las excepciones es problemático, probaremos actualizando\n",
    "la función `main()`:\n",
    "\n",
    "    def main():\n",
    "        try:\n",
    "            configuration = open('config.txt')\n",
    "        except Exception:\n",
    "            print(\"Couldn't find the config.txt file!\")\n",
    "\n",
    "Ahora volvemos a ejecutar el código en el mismo lugar donde existe el\n",
    "archivo *config.txt* con permisos incorrectos:\n",
    "\n",
    "    $ python config.py\n",
    "    Couldn't find the config.txt file!\n",
    "\n",
    "El problema ahora es que el mensaje de error es incorrecto. El archivo\n",
    "existe, pero tiene permisos diferentes y Python no puede leerlo. Cuando\n",
    "se trata con errores de software, puede resultar frustrante tener\n",
    "errores que hagan lo siguiente:\n",
    "\n",
    "-   No indiquen cuál es el problema real.\n",
    "-   Proporcionen una salida que no coincida con el problema real.\n",
    "-   No sugieran lo que se puede hacer para corregir el problema.\n",
    "\n",
    "Vamos a corregir este fragmento de código para abordar todas estas\n",
    "frustraciones. Revertiremos la detección de `FileNotFoundError` y luego\n",
    "agregamos otro bloque `except` para detectar `PermissionError`:\n",
    "\n",
    "    def main():\n",
    "        try:\n",
    "            configuration = open('config.txt')\n",
    "        except FileNotFoundError:\n",
    "            print(\"Couldn't find the config.txt file!\")\n",
    "        except IsADirectoryError:\n",
    "            print(\"Found config.txt but it is a directory, couldn't read it\")\n",
    "\n",
    "Ahora volvemos a ejecutarlo, en el mismo lugar donde *config.txt* está\n",
    "con el problema de permisos:\n",
    "\n",
    "    $ python config.py\n",
    "    Found config.txt but couldn't read it\n",
    "\n",
    "Eliminamos el archivo config.txt para asegurarnos de que se alcanza el\n",
    "primer bloque `except` en su lugar:\n",
    "\n",
    "    $ rm -f config.txt\n",
    "    $ python config.py\n",
    "    Couldn't find the config.txt file!\n",
    "\n",
    "Cuando los errores son de una naturaleza similar y no es necesario\n",
    "controlarlos individualmente, puedes agrupar las excepciones como una\n",
    "usando paréntesis en la línea `except`. Por ejemplo, si el sistema de\n",
    "navegación está bajo cargas pesadas y el sistema de archivos está\n",
    "demasiado ocupado, tiene sentido detectar `BlockingIOError` y\n",
    "`TimeOutError` juntos:\n",
    "\n",
    "    def main():\n",
    "        try:\n",
    "            configuration = open('config.txt')\n",
    "        except FileNotFoundError:\n",
    "            print(\"Couldn't find the config.txt file!\")\n",
    "        except IsADirectoryError:\n",
    "            print(\"Found config.txt but it is a directory, couldn't read it\")\n",
    "        except (BlockingIOError, TimeoutError):\n",
    "            print(\"Filesystem under heavy load, can't complete reading configuration file\")\n",
    "\n",
    "**Sugerencia**\n",
    "\n",
    "Aunque puedes agrupar excepciones, solo debes hacerlo cuando no sea\n",
    "necesario controlarlas individualmente. Evita agrupar muchas excepciones\n",
    "para proporcionar un mensaje de error generalizado.\n",
    "\n",
    "Si necesitas acceder al error asociado a la excepción, debes actualizar\n",
    "la línea `except` para incluir la palabra clave `as`. Esta técnica es\n",
    "práctica si una excepción es demasiado genérica y el mensaje de error\n",
    "puede ser útil:\n",
    "\n",
    "    >>> try:\n",
    "    ...     open(\"mars.jpg\")\n",
    "    ... except FileNotFoundError as err:\n",
    "    ...     print(\"got a problem trying to read the file:\", err)\n",
    "    ...\n",
    "    got a problem trying to read the file: [Errno 2] No such file or directory: 'mars.jpg'\n",
    "\n",
    "En este caso, `as err` significa que `err` se convierte en una variable\n",
    "con el objeto de excepción como valor. Después, usa este valor para\n",
    "imprimir el mensaje de error asociado a la excepción. Otra razón para\n",
    "usar esta técnica es acceder directamente a los atributos del error. Por\n",
    "ejemplo, si detecta una excepción `OSError` más genérica, que es la\n",
    "excepción primaria de `FilenotFoundError` y `PermissionError`, podemos\n",
    "diferenciarlas mediante el atributo `.errno`:\n",
    "\n",
    "    >>> try:\n",
    "    ...     open(\"config.txt\")\n",
    "    ... except OSError as err:\n",
    "    ...     if err.errno == 2:\n",
    "    ...         print(\"Couldn't find the config.txt file!\")\n",
    "    ...     elif err.errno == 13:\n",
    "    ...         print(\"Found config.txt but couldn't read it\")\n",
    "    ...\n",
    "    Couldn't find the config.txt file!\n",
    "\n",
    "Intenta usar siempre la técnica que proporcione la mejor legibilidad\n",
    "para el código y que ayude a mantenerlo en el futuro. A veces es\n",
    "necesario usar código menos legible para ofrecer una mejor experiencia\n",
    "de usuario cuando se produce un error.\n",
    "\n",
    "## Generación de excepciones\n",
    "\n",
    "Ahora que tienes una buena comprensión de los tracebacks y el control de\n",
    "excepciones, vamos a revisar la generación de excepciones.\n",
    "\n",
    "Es posible que ya conozcas una situación que podría provocar una\n",
    "condición de error al escribir código. En estas situaciones, resulta\n",
    "útil generar excepciones que permitan que otro código comprenda cuál es\n",
    "el problema.\n",
    "\n",
    "La generación de excepciones también puede ayudar en la toma de\n",
    "decisiones para otro código. Como hemos visto antes, en función del\n",
    "error, el código puede tomar decisiones inteligentes para resolver,\n",
    "solucionar o ignorar un problema.\n",
    "\n",
    "Los astronautas limitan su uso de agua a unos 11 litros al día. Vamos a\n",
    "crear una función que, con base al número de astronautas, pueda calcular\n",
    "la cantidad de agua quedará después de un día o más:\n",
    "\n",
    "    def water_left(astronauts, water_left, days_left):\n",
    "        daily_usage = astronauts * 11\n",
    "        total_usage = daily_usage * days_left\n",
    "        total_water_left = water_left - total_usage\n",
    "        return f\"Total water left after {days_left} days is: {total_water_left} liters\"\n",
    "\n",
    "PruProbemos con cinco astronautas, 100 litros de agua sobrante y dos\n",
    "días:\n",
    "\n",
    "    >>> water_left(5, 100, 2)\n",
    "    'Total water left after 2 days is: -10 liters'\n",
    "\n",
    "Esto no es muy útil, ya que una carencia en los litros sería un error.\n",
    "Después, el sistema de navegación podría alertar a los astronautas que\n",
    "no habrá suficiente agua para todos en dos días. Si eres un ingeniero(a)\n",
    "que programa el sistema de navegación, podrías generar una excepción en\n",
    "la función water_left() para alertar de la condición de error:\n",
    "\n",
    "    def water_left(astronauts, water_left, days_left):\n",
    "        daily_usage = astronauts * 11\n",
    "        total_usage = daily_usage * days_left\n",
    "        total_water_left = water_left - total_usage\n",
    "        if total_water_left < 0:\n",
    "            raise RuntimeError(f\"There is not enough water for {astronauts} astronauts after {days_left} days!\")\n",
    "        return f\"Total water left after {days_left} days is: {total_water_left} liters\"\n",
    "\n",
    "Ahora volvemos a ejecutarlo\n",
    "\n",
    "    >>> water_left(5, 100, 2)\n",
    "    Traceback (most recent call last):\n",
    "      File \"<stdin>\", line 1, in <module>\n",
    "      File \"<stdin>\", line 6, in water_left\n",
    "    RuntimeError: There is not enough water for 5 astronauts after 2 days!\n",
    "\n",
    "En el sistema de navegación, el código para señalar la alerta ahora\n",
    "puede usar `RuntimeError` para generar la alerta:\n",
    "\n",
    "    try:\n",
    "        water_left(5, 100, 2)\n",
    "    except RuntimeError as err:\n",
    "        alert_navigation_system(err)\n",
    "\n",
    "La función `water_left()` también se puede actualizar para evitar el\n",
    "paso de tipos no admitidos. Intentenis pasar argumentos que no sean\n",
    "enteros para comprobar la salida de error:\n",
    "\n",
    "    >>> water_left(\"3\", \"200\", None)\n",
    "    Traceback (most recent call last):\n",
    "      File \"<stdin>\", line 1, in <module>\n",
    "      File \"<stdin>\", line 3, in water_left\n",
    "    TypeError: can't multiply sequence by non-int of type 'NoneType'\n",
    "\n",
    "El error de `TypeError` no es muy descriptivo en el contexto de lo que\n",
    "espera la función. Actualizaremos la función para que use `TypeError`,\n",
    "pero con un mensaje mejor:\n",
    "\n",
    "    def water_left(astronauts, water_left, days_left):\n",
    "        for argument in [astronauts, water_left, days_left]:\n",
    "            try:\n",
    "                # If argument is an int, the following operation will work\n",
    "                argument / 10\n",
    "            except TypeError:\n",
    "                # TypError will be raised only if it isn't the right type \n",
    "                # Raise the same exception but with a better error message\n",
    "                raise TypeError(f\"All arguments must be of type int, but received: '{argument}'\")\n",
    "        daily_usage = astronauts * 11\n",
    "        total_usage = daily_usage * days_left\n",
    "        total_water_left = water_left - total_usage\n",
    "        if total_water_left < 0:\n",
    "            raise RuntimeError(f\"There is not enough water for {astronauts} astronauts after {days_left} days!\")\n",
    "        return f\"Total water left after {days_left} days is: {total_water_left} liters\"\n",
    "\n",
    "Ahora volvemos a intentarlo para obtener un error mejor:\n",
    "\n",
    "    >>> water_left(\"3\", \"200\", None)\n",
    "    Traceback (most recent call last):\n",
    "      File \"<stdin>\", line 5, in water_left\n",
    "    TypeError: unsupported operand type(s) for /: 'str' and 'int'\n",
    "\n",
    "    During handling of the preceding exception, another exception occurred:\n",
    "\n",
    "    Traceback (most recent call last):\n",
    "      File \"<stdin>\", line 1, in <module>\n",
    "      File \"<stdin>\", line 9, in water_left\n",
    "    TypeError: All arguments must be of type int, but received: '3'\n",
    "\n",
    "## Resumen\n",
    "\n",
    "Para ser un desarrollador eficaz, debes saber cómo funcionan las\n",
    "excepciones y cómo controlarlas. En este módulo, has descubierto cómo\n",
    "usar la salida de excepción para la depuración, cómo detectar y generar\n",
    "excepciones y, por último, cómo afecta a la lógica de un programa cuando\n",
    "se producen excepciones.\n",
    "\n",
    "Con los conocimientos del uso y el control de excepciones, puedes evitar\n",
    "problemas comunes, como detectarlos todos para evitar tracebacks.\n",
    "\n",
    "En este módulo, has obtenido información sobre estas aptitudes:\n",
    "\n",
    "-   Leer y usar la salida de error de las excepciones\n",
    "-   Controlar correctamente las excepciones\n",
    "-   Generar excepciones con mensajes de error útiles\n",
    "-   Usar excepciones para controlar el flujo de un programa\n",
    "\n",
    "## Kata del módulo 10\n",
    "\n",
    "Intenta realizar los ejercicios descritos en este documento.\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "Curso Propedútico de Python para Launch X - Innovacción Virtual.\n",
    "\n",
    "Material desarrollado con base en los contenidos de MSLearn y la\n",
    "metáfora de LaunchX, traducción e implementación por: Fernanda Ochoa -\n",
    "Learning Producer de LaunchX.\n",
    "\n",
    "Redes: \\* GitHub: [FernandaOchoa](https://github.com/FernandaOchoa) \\*\n",
    "Twitter: \\[@imonsh\\](https://twitter.com/imonsh) \\* Instagram:\n",
    "[fherz8a](https://www.instagram.com/fherz8a/)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
